name: organickinf
channels:
    - conda-forge
dependencies:
    - numpy
    - libopencv
    - opencv
    - py-opencv
    - pip
    - pip:
          - Jetson.GPIO
          - nvidia-pyindex
          - nvidia-tensorrt
          - onnxruntime-gpu
