name: organick
channels:
    - conda-forge
    - fastai
    - pytorch
dependencies:
    - fastai
    - numpy
    - matplotlib
    - jupyterlab
    - torchvision
    - opencv-python-headless
    - tqdm
